# Generated by Django 3.2.12 on 2022-04-18 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, default=None, upload_to='blogPictures')),
                ('category', models.CharField(blank=True, choices=[('Mental Health', 'Mental Health'), ('Heart Disease', 'Heart Disease'), ('Covid19', 'Covid19'), ('Immunization ', 'Immunization')], max_length=100, null=True)),
                ('summary', models.CharField(blank=True, max_length=500, null=True)),
                ('content', models.TextField(blank=True, max_length=5000, null=True)),
                ('isdraft', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.usermodel')),
            ],
            options={
                'verbose_name': 'Blog',
                'db_table': 'Blog',
            },
        ),
    ]
