# Generated by Django 3.2.12 on 2022-04-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_blogmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogmodel',
            options={'verbose_name_plural': 'Blog'},
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='isdraft',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
