# Generated by Django 3.2.12 on 2022-04-19 18:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_auto_20220418_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
